version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
    git: elsnoman
  MyUnitTests:
    title: Unit test
    stage: test
    image: 'mcr.microsoft.com/dotnet/core/sdk:3.0-alpine'
    commands:
      - dotnet test --filter testcategory=unit
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: stats-royale-tests
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
